mail:
  host: localhost
  port: 1025
  username: devraj
  password: password
  properties:
    mail:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enabled: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000