
db:
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: ecom-app


customer:
  service:
    url: http://localhost:8080/api/customer


payment:
  service:
    url: http://localhost:8000/api/payment

product:
  service:
    url: http://localhost:8090/api/products

notification:
  service:
    url: http://localhost:9095/api/notification